config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :friendships
  resources :posts, only: %i[index create] do
    resources :comments, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  root 'posts#index'
  get '/friendship/:id', to: 'friendships#follow'
  delete '/friendship/:id', to: 'friendships#unfollow'
  get '/users/:id', to: 'users#show', as: :show_user

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :user_id, :friend_id, presence: true
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
# rubocop: disable all

class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

# rubocop: disable all

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, presence: true, uniqueness: true
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships
  has_many :other_friendships, foreign_key: 'friend_id', class_name: 'Friendship'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      redirect_to posts_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.where(id: params[:id])[0]
    render 'show'
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[show edit update destroy]

  def follow
    Friendship.create(user_id: current_user.id, friend_id: params[:id])
    redirect_to root_path
  end

  def unfollow
    friendship = Friendship.where(user_id: current_user.id, friend_id: params[:id])
    friendship[0].destroy
    redirect_to root_path
  end

  private

  def set_friendship
    @friendship = Friendship.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(post_id: params[:post_id])

    if @like.save
      redirect_to posts_path, notice: 'Like'
    else
      redirect_to posts_path
    end
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, post_id: params[:post_id])
    like&.destroy
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.order('created_at DESC').includes([:user]).includes([:comments])
    @post = Post.new
    @user = User.all
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      redirect_to posts_path, alert: 'Post was not created.'
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def like_or_dislike_btn(post)
    like = Like.find_by(post: post, user: current_user)
    if like
      link_to('Dislike!', post_like_path(id: like.id, post_id: post.id), method: :delete)
    else
      link_to('Like!', post_likes_path(post_id: post.id), method: :post)
    end
  end

  def followers(user)
    followers = user.other_friendships.count
    followers
  end

  def following(user)
    following = user.friendships.count
    following
  end

  def follow(user)
    if current_user.friendships.where(friend_id: user.id).empty? && user.id != current_user.id
      link_to 'Follow', "/friendship/#{user.id}"
    elsif !current_user.friendships.where(friend_id: user.id).empty? && user.id != current_user.id
      link_to 'Unfollow', "/friendship/#{user.id}", method: 'delete'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
# rubocop: disable all

module LikesHelper
end

# rubocop: enabel all

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/likes/_form.html.erb
<%= form_with(model: like, local: true) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_follow.html.erb
<div >
	<div class="container" >
		<div class="bottom-nav mt-3">
			<span class="nav-title">WHO TO FOLLOW</span>
		</div>
		<div class="mt-3 title-color">

			<% @user.each do |user| %>
				<div class="d-flex">
					    <img class="icon-user mr-2" src="https://www.ub.edu/idp/web/sites/default/files/staff/2019-10/default-avatar.png">
					<div>
						<%= user.username  %><br>
						<span class="follow-link"><%= follow(user) %></span>
						<span class="follow-link"><%= link_to 'show', "/users/#{user.id}" %></span>
						<br><br>
					</div>
				</div>

			<% end %>
		</div>
		
	</div>
	<div></div>
	<div></div>
	



</div>

app/views/posts/index.html.erb
<div class=" bottom-left">
  <div class="bg-success text-center">
    <p id="notice " ><%= notice %></p>
  </div>
  <div class="bg-danger text-center"><p id="notice " ><%= alert %></p></div>
   <div class="bottom-nav d-flex mb-3">
      <span class="nav-bttn "><a href="/" class="hard-gray-text">POSTS</a></span>
      <span class="nav-bttn "><a href="/" class="hard-gray-text">PHOTOS</a></span>
      <span class="nav-bttn "><a href="/" class="hard-gray-text">VIDEOS</a></span>
    </div>
  <div class="container ">
   
    <div class="text-left">
      <div class=" conatiner bg-white pt-3 pl-3 pb-3 pr-3 rounded">
        <span class="title title-color">POST SOMETHING</span>  
        <%= form_for(@post) do |form| %>
          <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
          <% if @post.errors.full_messages.any? %>
            <p class="errors">
              <%= "Post could not be saved. #{@post.errors.full_messages.join('. ')}" %>
            </p>
          <% end %>
          <%= form.submit 'Post', class: 'btn btn-primary mt-1 twitter-color' %>
        <% end %>
      </div>
      <br>
      <div class="container border bg-white posts pt-1 pb-3">
        <div class="pt-3 pb-3 recent_post_border mb-3">
          <span class="twitter-text">Recent Posts</span><br>
        </div>
            <% @posts.each do |post| %>
            <div class="d-flex">
              <div>
                    <img class="icon-user mr-2" src="https://www.ub.edu/idp/web/sites/default/files/staff/2019-10/default-avatar.png">
              </div>
              <div class="post-right">
                <div class="d-flex justify-content-between">
                  <%= post.user.username %><br>
                  <%= like_or_dislike_btn(post) %>
                </div>
                <span class="gray-text"><%= post.content %></span><br>
                
                <span>Likes: <%= post.likes.count %><br></span>
                <div>
                  <% post.comments.each do |comment| %>
                  
                      <span><%= comment.user.username %> : <%= comment.content %><br> </span>

                  <% end %>
                  <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
                    <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
                    <%= form.submit 'Comment', class: 'btn btn-secondary mt-2 mb-2' %>
                  <% end %>
                </div>     
              </div>
            </div>
            <% end %>
      </div>
      <br>
    </div>
  </div>
</div>
<div class="botton-right">
  <%= render 'follow' %>
  
</div>

app/views/users/show.html.erb
<div class="bottom-left">
	<img class="cover-img" src="https://coverfiles.alphacoders.com/144/144992.jpg">
	<div class="bottom-nav d-flex mb-3 mt-3">
      <span class="nav-bttn "><a href="/" class="hard-gray-text">POSTS</a></span>
      <span class="nav-bttn "><a href="/" class="hard-gray-text">PHOTOS</a></span>
      <span class="nav-bttn "><a href="/" class="hard-gray-text">VIDEOS</a></span>
    </div>
    <div>
    	<div class="container ">
		    <div class="container bg-white posts pt-3 pb-3 border" >
		    	<div class="border-bottom pb-2">
		    		<span class="twitter-text bold">ALL POSTS</span>
		    	</div>
		    	<div>
		    		<% @user.posts.each do |post| %>
		    			<div class="d-flex mt-3 mb-3 ">
		    				    <img class="icon-user mr-2" src="https://www.ub.edu/idp/web/sites/default/files/staff/2019-10/default-avatar.png">
			    			<div>
			    				<%= @user.username %><br>
			    				<span class="gray-text"><%= post.content %></span>

			    			</div>


		    			</div>
		    		<% end %>
		    	</div>
		    </div>
		</div>
	</div>



</div>
<div class="bottom-right ">
	<div class="text-center total-width mt-3">
	
		    <img class="icon-user-show mr-2" src="https://www.ub.edu/idp/web/sites/default/files/staff/2019-10/default-avatar.png"><br>
		<span class=" mt-3 "><%= @user.username %></span><br>
		<span class=" mt-3  gray-text"><%= @user.email %></span><br>
		<% if @user.id != current_user.id %>
			<span class="follow-bttn mt-3"><%= follow(@user) %></span>
		<% end %>
		<div class="d-flex justify-content-between border mt-3 pl-2 pr-2">
			<div class="border-right pr-2 mr-2">
				<span><%= @user.posts.count %></span><br>
				<span class="gray-text">Posts</span>
			</div>
			<div>
				<span ><%=  following(@user) %></span><br>
				<span class="gray-text">Following</span>
			</div>
			<div class="border-left pl-2 ml-2" >
				<span ><%=  followers(@user) %> </span><br>
              <span class="gray-text">Followers</span>
			</div>
			
		</div>

	</div>
	<div class="pl-2 pt-3 border-bottom pb-3">
		<span class="gray-text ">FOLLOWED BY</span>
	</div>
	<div >
		<% @user.other_friendships.each do |user| %>
			<div class="d-flex mt-3 pl-2">
			<img class="icon-user mr-2" src="https://cdn.iconscout.com/icon/free/png-512/avatar-375-456327.png">
			
			<div>
				<span class="bold"><%= user.user.username %></span><br>
				<span class="gray-text"><%= user.user.email %> </span><br>
				<span class="follow-link"><%= follow(user.user) %></span>
			</div>
			</div>
		<% end %><br>
	</div>

</div>